[package]
name = "test-token"
version = "0.1.0"
authors = ["Illia Polosukhin <illia.polosukhin@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
near-sdk = {version="5.9.0", features = ["unit-testing"] }
near-contract-standards = "5.9.0"
